/*
 * This file is part of Espruino, a JavaScript interpreter for Microcontrollers
 *
 * Copyright (C) 2026 Simon Andrews
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef XFSM_INTERNAL_H
#define XFSM_INTERNAL_H

#include "jsutils.h"

#define XFC_MACHINE_ARENA_NAME JS_HIDDEN_CHAR_STR "xfcA"
#define XFC_MACHINE_RETAINED_NAME JS_HIDDEN_CHAR_STR "xfcR"
#define XFC_MACHINE_BRAND_NAME JS_HIDDEN_CHAR_STR "xfcM"

#define XFC_ASSIGN_BRAND_NAME JS_HIDDEN_CHAR_STR "xfcB"
#define XFC_ASSIGN_VALUE_NAME JS_HIDDEN_CHAR_STR "xfcV"

#define XFC_ACTOR_BRAND_NAME JS_HIDDEN_CHAR_STR "xfaB"
#define XFC_ACTOR_MACHINE_NAME JS_HIDDEN_CHAR_STR "xfaM"
#define XFC_ACTOR_DATA_NAME JS_HIDDEN_CHAR_STR "xfaD"
#define XFC_ACTOR_CONTEXT_NAME JS_HIDDEN_CHAR_STR "xfaC"
#define XFC_ACTOR_SNAPSHOT_NAME JS_HIDDEN_CHAR_STR "xfaS"
#define XFC_ACTOR_ERROR_NAME JS_HIDDEN_CHAR_STR "xfaE"
#define XFC_ACTOR_SUBSCRIPTIONS_NAME JS_HIDDEN_CHAR_STR "xfaL"
#define XFC_ACTOR_SUBSCRIPTION_SEQUENCE_NAME JS_HIDDEN_CHAR_STR "xfaN"

#define XFC_SNAPSHOT_BRAND_NAME JS_HIDDEN_CHAR_STR "xfsB"
#define XFC_SNAPSHOT_MACHINE_NAME JS_HIDDEN_CHAR_STR "xfsM"
#define XFC_SNAPSHOT_LEAF_NAME JS_HIDDEN_CHAR_STR "xfsL"

#define XFC_SUBSCRIPTION_BRAND_NAME JS_HIDDEN_CHAR_STR "xfuB"
#define XFC_SUBSCRIPTION_ACTOR_NAME JS_HIDDEN_CHAR_STR "xfuA"
#define XFC_SUBSCRIPTION_LISTENER_NAME JS_HIDDEN_CHAR_STR "xfuL"
#define XFC_SUBSCRIPTION_SEQUENCE_NAME JS_HIDDEN_CHAR_STR "xfuN"

#define XFC_ROOT_MACHINE_TOKEN JS_HIDDEN_CHAR_STR "xfTM"
#define XFC_ROOT_ACTOR_TOKEN JS_HIDDEN_CHAR_STR "xfTA"
#define XFC_ROOT_SNAPSHOT_TOKEN JS_HIDDEN_CHAR_STR "xfTS"
#define XFC_ROOT_SUBSCRIPTION_TOKEN JS_HIDDEN_CHAR_STR "xfTU"
#define XFC_ROOT_UNDEFINED_EXCEPTION JS_HIDDEN_CHAR_STR "xfTE"
#define XFC_ROOT_ACTOR_PROTOTYPE JS_HIDDEN_CHAR_STR "xfPA"
#define XFC_ROOT_SNAPSHOT_PROTOTYPE JS_HIDDEN_CHAR_STR "xfPS"
#define XFC_ROOT_SUBSCRIPTION_PROTOTYPE JS_HIDDEN_CHAR_STR "xfPU"

#endif
